--- !ditz.rubyforge.org,2008-03-06/project 
name: nul
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: nul
- !ditz.rubyforge.org,2008-03-06/component 
  name: sigma0
- !ditz.rubyforge.org,2008-03-06/component 
  name: vancouver
- !ditz.rubyforge.org,2008-03-06/component 
  name: runtime
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.2"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2010-07-29 10:58:29.540837 Z
    - Julian Stecklina <jsteckli@os.inf.tu-dresden.de>
    - created
    - ""
